apiVersion: apps/v1
kind: Deployment
metadata:
  name:  python-k8s-demo
  namespace: default
  labels:
    app:  python-k8s-demo
spec:
  selector:
    matchLabels:
      app: python-k8s-demo
  replicas: 1
  template:
    metadata:
      labels:
        app:  python-k8s-demo
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  python-k8s-demo
        image:  umarisbwaqas/python-k8s-demo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  5000

---
apiVersion: v1
kind: Service
metadata:
  name: python-k8s-demo
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: python-k8s-demo
  ports:
  - name: python-k8s-demo
    protocol: TCP
    port: 80
    targetPort: 5000
