version: "3.2"
 
services:

    jenkins:
        image: jenkins
        container_name: jenkins-container
        build:
            context: ./jenkins
        restart: always
        networks:
            - sonarnet
        ports:
            - "8080:8080"
            - '50000:50000'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '~/data/jenkins/jenkins_home:/var/jenkins_home'
            - '~/.kube:/root/.kube:ro'
        user: root
       
    # web:
    #     image: 'gitlab/gitlab-ee:latest'
    #     restart: always
    #     hostname: 'gitlab.example.com'

    #     ports:
    #      - '80:80'
    #      - '443:443'
    #      - '22:22'
    #     volumes:
    #       - '~/data/gitlab/config:/etc/gitlab'
    #       - '~/data/gitlab/logs:/var/log/gitlab'
    #       - '~/data/gitlab/data:/var/opt/gitlab'
    #     shm_size: '256m'

    sonarqube:
        image: sonarqube:community
        container_name: sonar-container
        restart: always
        depends_on:
            - postgressdb
        networks:
            - sonarnet
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=Passw0rd1
            - SONARQUBE_JDBC_URL=jdbc:postgresql://postgressdb:5432/sonarqube
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - "9000:9000"
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
  
    postgressdb:
        image: postgres:13
        container_name: postgres-container
        restart: always
        networks:
            - sonarnet
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=Passw0rd1
            - POSTGRES_DB=sonarqube
        volumes:
            - postgresql_data:/var/lib/postgresql/data
 
networks:
    sonarnet:
        driver: bridge

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql_data: